server:
  port: 3000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/amazon_clone
    username: root
    password: abc123456
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
  jackson:
    serialization:
      fail-on-empty-beans: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: amazon.team016@gmail.com
    password: '*Abc123456'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

secretKey: fPJZz!YkEmUhdmvvhw7y*6K*0$7vco!pfiOtq6N&cgnLNT$I4u